### ISSUE TITLE
Update the serverless runtime example image

### ISSUE THREAD

**Issue by remi-sap** [kyma-project/examples#211]
Hello,
I've noticed some difference between the example serverless python runtime docker image and the one running in my Kyma cluster.
Could you please either:
* sync [kubeless.py](https://github.com/kyma-project/examples/blob/main/custom-serverless-runtime-image/kubeless/kubeless.py) so it is identical to the version running in the cluster?
* publish the current image for python serverless runtime, so I can use inheritance to extend it ?

**Description**

Reference image for python runtime seems outdated.

**Reasons**

I need to customize the python runtime image (only to `apt install` an OS package). I don't want to encounter regressions because I used an outdated reference image.

Thanks.

**Comment by kwiatekus** [comment]
the example based on python:bullseye doesnt work with our tracing library
This needs further investigation
```
Traceback (most recent call last):
  File "//kubeless.py", line 12, in <module>
    import tracing
  File "/tracing.py", line 7, in <module>
    from opentelemetry.exporter.otlp.proto.http.trace_exporter import OTLPSpanExporter
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/__init__.py", line 40, in <module>
    from opentelemetry.exporter.otlp.proto.http.trace_exporter.encoder import (
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/exporter/otlp/proto/http/trace_exporter/encoder/__init__.py", line 19, in <module>
    from opentelemetry.proto.collector.trace.v1.trace_service_pb2 import (
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/proto/collector/trace/v1/trace_service_pb2.py", line 14, in <module>
    from opentelemetry.proto.trace.v1 import trace_pb2 as opentelemetry_dot_proto_dot_trace_dot_v1_dot_trace__pb2
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/proto/trace/v1/trace_pb2.py", line 14, in <module>
    from opentelemetry.proto.common.v1 import common_pb2 as opentelemetry_dot_proto_dot_common_dot_v1_dot_common__pb2
  File "/usr/local/lib/python3.9/site-packages/opentelemetry/proto/common/v1/common_pb2.py", line 36, in <module>
    _descriptor.FieldDescriptor(
  File "/usr/local/lib/python3.9/site-packages/google/protobuf/descriptor.py", line 560, in __new__
    _message.Message._CheckCalledFromGeneratedFile()
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
